# Generated by Django 3.1.5 on 2021-01-27 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytodo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='complete',
        ),
        migrations.AddField(
            model_name='todo',
            name='completion_status',
            field=models.CharField(choices=[('todo', 'todo'), ('doing', 'doing'), ('done', 'done')], default=None, max_length=5),
        ),
    ]
