# Generated by Django 3.1.5 on 2021-01-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytodo', '0002_auto_20210127_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='completion_status',
            field=models.BooleanField(),
        ),
    ]
