# Generated by Django 3.1.5 on 2021-01-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytodo', '0003_auto_20210127_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='completion_status',
            field=models.BooleanField(default=False),
        ),
    ]
